### ISSUE TITLE
Does Sinon.js support mocking native node.js modules, such as ZMQ?

### ISSUE THREAD

**Issue by grandtiger** [sinonjs/sinon#1153]
This is a general question. Does Sinon.js support mocking of native node.js modules, such as ZMQ? https://www.npmjs.com/package/zmq

I tried to mock it and got the following error. If native module is supported by design, I'll provide a simple project for you to replicate the issue. Thanks a lot for your help!

```
Error: Invalid argument
 at Error (native)
 at ._fd (D:\temp\sinonzmq\node_modules\zmq\lib\index.js:397:22)
 at D:\temp\sinonzmq\node_modules\sinon\lib\sinon\walk.js:28:50
 at Array.forEach (native)
 at walkInternal (D:\temp\sinonzmq\node_modules\sinon\lib\sinon\walk.js:23:45)
 at walkInternal (D:\temp\sinonzmq\node_modules\sinon\lib\sinon\walk.js:34:17)
 at Object.walk (D:\temp\sinonzmq\node_modules\sinon\lib\sinon\walk.js:49:20)
 at Object.stub (D:\temp\sinonzmq\node_modules\sinon\lib\sinon\stub.js:52:23)
 at Context.<anonymous> (D:\temp\sinonzmq\test\trade-manager-spec.js:23:24)
 at callFn (C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:286:21)
 at Test.Runnable.run (C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:279:7)
 at Runner.runTest (C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:10)
 at C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:12
 at next (C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:14)
 at C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7
 at next (C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:283:14)
 at Immediate._onImmediate (C:\Users\f401036\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

```

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by grandtiger** [comment]
Thanks for the message! I just posted a new topic to the mailing list.
