### ISSUE TITLE
Typerror thrown when trying to match on objects without `hasOwnProperty` method

### ISSUE THREAD

**Issue by madtrick** [sinonjs/sinon#1245]
* Sinon version : 1.17.0
* Environment   : node
* Example URL   :
* Other libraries you are using: sinon-chai

**What did you expect to happen?**
Using the `calledWithMatch` to work also with objects which don't have a `hasOwnProperty` function.

**What actually happens**
The error `TypeError: expectation.hasOwnProperty is not a function` is thrown

**How to reproduce**

```js
it('fails', function () {
  sinon.spy(library, 'method');

  const objectWithoutPrototype = Object.create(null);
  objectWithoutPrototype.something = 2;

  library.method({foo: 1, objectWithoutPrototype})

  expect(library.method).to.have.been.calledWithMatch({ objectWithoutPrototype});
});
```

<details>
    TypeError: expectation.hasOwnProperty is not a function
      at matchObject (node_modules/sinon/lib/sinon/match.js:42:33)
      at matchObject (node_modules/sinon/lib/sinon/match.js:50:30)
      at matchObject (node_modules/sinon/lib/sinon/match.js:50:30)
      at Object.m.test (node_modules/sinon/lib/sinon/match.js:80:28)
      at Object.calledWithMatch (node_modules/sinon/lib/sinon/call.js:60:67)
      at Function.spyApi.(anonymous function) [as calledWithMatch] (node_modules/sinon/lib/sinon/spy.js:330:55)
      at Assertion.<anonymous> (node_modules/sinon-chai/lib/sinon-chai.js:95:48)
      at Assertion.ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at Assertion.<anonymous> (node_modules/dirty-chai/lib/dirty-chai.js:181:23)
      at Assertion.ctx.(anonymous function) [as calledWithMatch] (node_modules/chai/lib/chai/utils/overwriteMethod.js:48:33)
</details>

**Comment by madtrick** [comment]
This seems to be similar in nature to this other issue https://github.com/sinonjs/sinon/issues/887

**Comment by mroderick** [comment]
Thank you for your concise bug report.

⭐️ for providing a failing test case

**Comment by mroderick** [comment]
@madtrick I've created #1254 to verify that this bug doesn't exist in the next version of Sinon (`sinon@next`, it's the `master` branch).

Since we use ES5 in the codebase, I had to slightly modify your test. Would you mind looking it over, to see if I have translated it correctly and that it still covers your scenario?

Also: it would be great if you could try to verify the absence of the error in `sinon@next` when used in your codebase.

```shell
npm install sinon@next
```

**Comment by mroderick** [comment]
@madtrick would you mind trying to reproduce this bug with `sinon@next`?
