### ISSUE TITLE
Cryptic error when calling spy

### ISSUE THREAD

**Issue by andreyluiz** [sinonjs/sinon#1267]
I have a spy which I am passing as a prop in a react component. This spy should count and get args when the form's submit is triggered.

In the above example I am getting the call count and trying to get the call arguments:

```javascript
const store = mockStore({
    form: {},
});

const onSubmit = sinon.spy();

const wrapper = mount(
    <Provider store={store}>
    <MemoryRouter>
        <ForgotForm onSubmit={onSubmit} />
    </MemoryRouter>
    </Provider>,
);

wrapper.find('input#email').simulate('change', { target: { value: 'andrey.luiz@datarisk.io' } });
wrapper.find('form').simulate('submit');

console.log(onSubmit.callCount); // outputs 1
console.log(onSubmit.getCall(0).callArg(0)); // TypeError: this.args[pos] is not a function
```
As commented, the last command returns an error. Inspecting the spy, there's a cryptic error in the `stacks` parameter:

```
Error
    at Function.invoke (/home/andrey/Projects/Datarisk/app-frontend/node_modules/sinon/lib/sinon/spy.js:191:40)
    at proxy (/home/andrey/Projects/Datarisk/app-frontend/node_modules/sinon/lib/sinon/spy.js:85:30)
    at doSubmit (/home/andrey/Projects/Datarisk/app-frontend/node_modules/redux-form/lib/handleSubmit.js:42:20)
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/redux-form/lib/handleSubmit.js:107:14
    at handleSubmit (/home/andrey/Projects/Datarisk/app-frontend/node_modules/redux-form/lib/handleSubmit.js:110:6)
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/redux-form/lib/reduxForm.js:537:98
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/redux-form/lib/events/silenceEvents.js:19:52
    at Object.invokeGuardedCallback [as invokeGuardedCallbackWithCatch] (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactErrorUtils.js:26:5)
    at executeDispatch (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/EventPluginUtils.js:83:21)
    at Object.executeDispatchesInOrder (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/EventPluginUtils.js:108:5)
    at executeDispatchesAndRelease (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseSimulated (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/EventPluginHub.js:51:10)
    at forEachAccumulated (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/forEachAccumulated.js:26:8)
    at Object.processEventQueue (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/EventPluginHub.js:255:7)
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactTestUtils.js:340:22
    at ReactDefaultBatchingStrategyTransaction.perform (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/Transaction.js:140:20)
    at Object.batchedUpdates (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactUpdates.js:97:27)
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/react-dom/lib/ReactTestUtils.js:338:18
    at ReactWrapper.<anonymous> (/home/andrey/Projects/Datarisk/app-frontend/node_modules/enzyme/build/ReactWrapper.js:776:11)
    at ReactWrapper.single (/home/andrey/Projects/Datarisk/app-frontend/node_modules/enzyme/build/ReactWrapper.js:1421:25)
    at ReactWrapper.simulate (/home/andrey/Projects/Datarisk/app-frontend/node_modules/enzyme/build/ReactWrapper.js:769:14)
    at Context.<anonymous> (/home/andrey/Projects/Datarisk/app-frontend/specs/integration/forms/ForgotForm.js:64:26)
    at callFn (/home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runnable.js:345:21)
    at Test.Runnable.run (/home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runnable.js:337:7)
    at Runner.runTest (/home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runner.js:444:10)
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runner.js:550:12
    at next (/home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runner.js:361:14)
    at /home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runner.js:371:7
    at next (/home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/home/andrey/Projects/Datarisk/app-frontend/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:649:20)

   at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

I have no idea why this error occurs, but I think it is related to the missing arguments. Does someone know what this error is about?

**Comment by lucasfcosta** [comment]
Hi @andreyluiz, it's nice to see more people from Florianópolis here 😄 

I was taking a look at Sinon's source code and apparently what happens when you get an specific call from a spy is:

1. [It checks if this call exists (if its greater than `0` and lesser or equal than the total count of calls)](https://github.com/sinonjs/sinon/blob/6dd1114c524cc0ef2c9ae098749a509da4dc86f7/lib/sinon/spy.js#L239)
2. [It creates an instance of `callProto` with this call's data](https://github.com/sinonjs/sinon/blob/6dd1114c524cc0ef2c9ae098749a509da4dc86f7/lib/sinon/call.js#L187)

The problem is that (apparently) there's somewhere we're trying to invoke one of the args passed (which is not a function).

I don't see how that can happen by looking at the code on the master branch. Can you please provide us the version number you're using so we can check its specific code?

Let me know if I missed anything.

**Comment by mroderick** [comment]
There has been no response from OP for several months, I am closing this
