### ISSUE TITLE
Incompatibility with recent versions of Babel

### ISSUE THREAD

**Issue by jlecomte** [sinonjs/sinon#1316]
* Sinon version : Both 1.17.7 and 2.0.0-pre6
* Environment   : Node v6.9.1
* Example URL   : N/A
* Other libraries you are using: babel-register@6.23.0

**Test case**

index.js:
```
require('babel-register')();
require('./test.js');
```

test.js:
```
var sinon = require('sinon');
sinon.stub(Math, 'random');
```

Command:

```
node index.js
```

**What did you expect to happen?**

Nothing...

**What actually happens**

An error is thrown:

```
/path/to/my/app/node_modules/sinon/lib/sinon/util/core.js:154
            method.stackTrace = (new Error("Stack Trace for original")).stack;
                                                                       ^
TypeError: Cannot read property 'generatedLine' of undefined
    at compareByGeneratedPositionsDeflated (/path/to/my/app/node_modules/source-map/lib/util.js:344:46)
    at doQuickSort (/path/to/my/app/node_modules/source-map/lib/quick-sort.js:88:11)
    at exports.quickSort (/path/to/my/app/node_modules/source-map/lib/quick-sort.js:113:3)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/path/to/my/app/node_modules/source-map/lib/source-map-consumer.js:519:5)
    at SourceMapConsumer.get (/path/to/my/app/node_modules/source-map/lib/source-map-consumer.js:68:12)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/path/to/my/app/node_modules/source-map/lib/source-map-consumer.js:606:11)
    at mapSourcePosition (/path/to/my/app/node_modules/source-map-support/source-map-support.js:196:42)
    at wrapCallSite (/path/to/my/app/node_modules/source-map-support/source-map-support.js:339:20)
    at /path/to/my/app/node_modules/source-map-support/source-map-support.js:374:26
    at Array.map (native)
```

**Comment by jlecomte** [comment]
This started with babel-register@6.16.0 due to the upgrade of source-map-support. Maybe I should file an issue in Babel?

**Comment by fatso83** [comment]
This looks like a problem with Babel ... I am not at all convinced this is a Sinon issue. It looks like the source map module has problems generating a correct stack trace. in the 0.4.3 version.

**Comment by jlecomte** [comment]
I filed the following issue on the Babel repo:

https://github.com/babel/babel/issues/5426

Thanks!

**Comment by loganfsmyth** [comment]
Fun times: https://github.com/babel/babel/issues/5426#issuecomment-284839994
