### ISSUE TITLE
Cannot read property 'method' of undefined

### ISSUE THREAD

**Issue by mir3z** [sinonjs/sinon#1399]
* Sinon version : 2.2.0
* Environment   : node
* Example URL   :
* Other libraries you are using:

**What did you expect to happen?**
I expect meaningful failure message.

**What actually happens**

Exception thrown:
```
TypeError: Cannot read property 'method' of undefined
    at node_modules/sinon/lib/sinon/mock-expectation.js:182:42
    at Array.forEach (native)
    at Function.verifyCallAllowed (node_modules/sinon/lib/sinon/mock-expectation.js:175:27)
    at Function.invoke (node_modules/sinon/lib/sinon/mock-expectation.js:78:14)
    at proxy (node_modules/sinon/lib/sinon/spy.js:97:22)
```

**How to reproduce**
```
        import { mock } from "sinon";

        const m = mock().withArgs(5);

        m(10);

        m.verify();
```

**Comment by mroderick** [comment]
Thank you for the bug report!

I have verified this bug locally, using a further reduced case (that works straight in node), and will also work in Mocha

```javascript
const sinon = require('sinon');
const m = sinon.mock().withArgs(5);

m(10);
```

**Comment by nschurmann** [comment]
I want to provide more info to this bug, sinon 2.2.0
```javascript
describe('queryTrack', () => {
  it('queries track by timeDelta', () => {
    const args = { dateRegister: { $gt: new Date('2017-01-12T18:16:31.065Z') }, userId: 'userId' }
    TracksMock.exec.resolves([])
    TracksMock.find.once()
    TracksMock.find.withArgs(args) // <-- this line fails!
    return queryTrack({ Tracks: TracksMock, timeDelta: new Date(1496081791065), userId: 'userId' })
      .then(() => {
        TracksMock.find.verify()
        expect(TracksMock.exec.calledOnce).to.be.true
      })
  })
})
```

Throws the same error:

```
TypeError: Cannot read property 'method' of undefined
      at node_modules/sinon/lib/sinon/mock-expectation.js:182:42
      at Array.forEach (native)
      at Function.verifyCallAllowed (node_modules/sinon/lib/sinon/mock-expectation.js:175:27)
      at Function.invoke (node_modules/sinon/lib/sinon/mock-expectation.js:78:14)
      at Object.proxy [as find] (node_modules/sinon/lib/sinon/spy.js:97:22)
      at exports.queryTrack (resolver/tracking-callback.js:16:10)
      at Context.<anonymous> (resolver/tracking-callback.spec.js:53:47)
```
