### ISSUE TITLE
Sinon 4.4.8 Node 8.9.4 throws "Error: Cannot find module '@sinonjs/formatio'" error

### ISSUE THREAD

**Issue by shwetasabne** [sinonjs/sinon#1750]
* Sinon version : v4.4.8
* Environment   : macOS Sierra, Node version 8.9.4

**What did you expect to happen?**
Using sinon 4.4.8 throws the following error:
```
module.js:540
    throw err;
    ^

Error: Cannot find module '@sinonjs/formatio'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ssabne/testProject/node_modules/sinon/lib/sinon/util/core/format.js:3:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**What actually happens**
See above for the error

**How to reproduce**
Install sinon using `npm install sinon`

Create a small test file: (test123.js)
```
const sinon = require('sinon');
```
Now run the test file `node test123.js`

**Comment by hurkanakbiyik** [comment]
@shwetasabne How did you solve it?

**Comment by fatso83** [comment]
@hurkanakbiyik He probably did one of two things:
1. `rm -r node_modules; npm install`
1. `npm install sinon@latest`

Both will probably have fixed it.
