### ISSUE TITLE
Can not install sinon via yarn 

### ISSUE THREAD

**Issue by bidorboocrew** [sinonjs/sinon#1883]
**Describe the bug**

**To Reproduce**
install yarn 1.9.4
then execute this command
yarn add sinon 

**Expected behavior**
to install the sinon package successfully

**Screenshots**
instead I get this following error 
```
:/opt/src/enterpriseweb$ yarn add sinon
yarn add v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
error Couldn't find package "@sinonjs/commons@^1.0.1" required by "sinon" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@sinonjs/samsam@^2.0.0" required by "sinon" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/saidm/.yarn/lib/cli.js:243:66)
    at new MessageError (/home/saidm/.yarn/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/home/saidm/.yarn/lib/cli.js:38988:17)
    at Generator.throw (<anonymous>)
    at step (/home/saidm/.yarn/lib/cli.js:92:30)
    at /home/saidm/.yarn/lib/cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```
**Context (please complete the following information):**

* Library version: _please verify that the bug exists in the latest release_
* Environment:
* Example URL:
* Other libraries you are using:

**Additional context**
I feel this should be looked into as it is a blocker from using the library

**Comment by mantoni** [comment]
I tried to reproduce, but it worked for me. This is what I did:

```
❯ mkdir sinon-yarn-issue
❯ cd sinon-yarn-issue/
❯ yarn add sinon
yarn add v1.9.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Saved lockfile.
success Saved 15 new dependencies.
info Direct dependencies
└─ sinon@6.1.5
info All dependencies
├─ @sinonjs/commons@1.0.2
├─ @sinonjs/samsam@2.0.0
├─ diff@3.5.0
├─ has-flag@3.0.0
├─ isarray@0.0.1
├─ just-extend@1.1.27
├─ lodash.get@4.4.2
├─ lolex@2.7.1
├─ nise@1.4.3
├─ path-to-regexp@1.7.0
├─ samsam@1.3.0
├─ sinon@6.1.5
├─ supports-color@5.5.0
├─ text-encoding@0.6.4
└─ type-detect@4.0.8
✨  Done in 2.09s.
```

Maybe you should follow the instructions given in the yarn warning and remove `package-lock.json` before installing?

**Comment by bidorboocrew** [comment]
Thank you so much .

Yes the first issue was caused because my project had yarn lock file + package-lock.json which is auto generated in the latest npm vs .

once removed both and reinstalled I was able to get this working .

please mark this as resolved !
