### ISSUE TITLE
Error: Cannot find module './util/fake_timers'

### ISSUE THREAD

**Issue by cartant** [sinonjs/sinon#1938]
**Describe the bug**

After running `yarn upgrade` in [`rxjs-etc`](https://github.com/cartant/rxjs-etc/), the Node mocha test runner fails will the following error:

```
$ mocha build/**/*-spec.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './util/fake_timers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Nicholas\git\github\rxjs-etc\node_modules\sinon\lib\sinon\sandbox.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Nicholas\git\github\rxjs-etc\node_modules\sinon\lib\sinon\create-sandbox.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Nicholas\git\github\rxjs-etc\node_modules\sinon\lib\sinon.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Nicholas\git\github\rxjs-etc\build\scheduler\enterZone-spec.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at C:\Users\Nicholas\git\github\rxjs-etc\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Nicholas\git\github\rxjs-etc\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\Nicholas\git\github\rxjs-etc\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\Nicholas\git\github\rxjs-etc\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
$
```

The semver in the project's `package.json` is `^7.0.0` and prior to the upgrade, version `7.0.0` did not effect the error.

**To Reproduce**

* Clone the [`rxjs-etc`](https://github.com/cartant/rxjs-etc/) repo.
* Run `yarn upgrade && yarn test`.

**Expected behavior**

No error, with tests passing as with `7.0.0`.

**Screenshots**

N/A

**Context (please complete the following information):**

* Library version: 7.1.0
* Environment: Node 10.11.0
* Example URL: N/A
* Other libraries you are using: `mocha`

**Additional context**

No

**Comment by fatso83** [comment]
We don't support `yarn`. I would try removing the modules directory manually (`rm -rf node_modules`) and installing again. I expect something like a yarn error to be the case, since I haven't heard from anyone lse.
