### ISSUE TITLE
Upgrade from 4.5.0 to 5.1.1 Unable to use FakeXHR

### ISSUE THREAD

**Issue by d1820** [sinonjs/sinon#1944]
**Describe the bug**

upon upgrade of package a compile error happens

 TypeError: Cannot read property 'replace' of undefined
        at normalizeHeaderValue (node_modules/sinon/pkg/sinon.js:9193
:18)
        at FakeXMLHttpRequest.setRequestHeader (/node_modules/sinon/pk
g/sinon.js:9533:17)
        at setRequestHeader (index.js:106536:19)
        at Object.forEach (index.js:40945:12)
        at dispatchXhrRequest (index.js:106530:13)
        at new Promise (<anonymous>)
        at xhrAdapter (index.js:106422:10)
        at dispatchRequest (index.js:144595:10)

**normalizeHeaderValue** does not check if value is populated before executing regex

Usage in test
```js
it.only('should add Ocp-Apim-Subscription-Key header when base request made', async () => {
        let callback = (xhr: any, requestIndex: number) => {
            console.test(xhr);
            responseFunc = testHelper.mockXhrResponse(0, '[]', 500);
            responseFunc();

        };

this._fakeXhr = sinon.useFakeXMLHttpRequest();
        this._fakeXhr.requestHeaders = {
            "Accept": "application/json, */*",
            "Connection": "keep-alive"
        };
        this._xhrRequests = [];
        this._fakeXhr.onCreate = xhr => {
            this._xhrRequests.push(xhr);
            if (callback ) {
                callback (xhr, this._xhrRequests.length - 1);
            }
        };

}
```

**Expected behavior**
Test works as expected from version 4.5.0 since nothing in the upgrade docs mentions any changes to this area.

**Context (please complete the following information):**

* Library version: _please verify that the bug exists in the latest release_
```
 "@types/chai": "4.1.7",
        "@types/googlemaps": "3.30.11",
        "@types/hammerjs": "2.0.36",
        "@types/lodash": "4.14.118",
        "@types/mocha": "5.2.0",
        "@types/node": "9.6.6",
        "@types/sinon": "4.3.1",
        "@types/storejs": "2.0.2",
        "@types/webpack-env": "1.13.6",
        "aspnet-prerendering": "3.0.1",
        "aspnet-webpack": "2.0.3",
        "avoriaz": "6.3.0",
        "babel-core": "6.26.3",
        "babel-loader": "7.1.5",
        "babel-polyfill": "6.26.0",
        "babel-preset-env": "1.7.0",
        "bind-decorator": "1.0.11",
        "chai": "4.2.0",
        "chalk": "2.4.0",
        "copy-webpack-plugin": "4.5.1",
        "cross-env": "5.2.0",
        "css-loader": "0.28.11",
        "extract-text-webpack-plugin": "3.0.2",
        "file-loader": "1.1.11",
        "istanbul-instrumenter-loader": "3.0.1",
        "json-loader": "0.5.7",
        "karma": "3.1.1",
        "karma-chrome-launcher": "2.2.0",
        "karma-coverage": "1.1.2",
        "karma-coverage-istanbul-reporter": "2.0.4",
        "karma-es6-shim": "1.0.0",
        "karma-intl-shim": "1.0.3",
        "karma-mocha": "1.3.0",
        "karma-mocha-reporter": "2.2.5",
        "karma-phantomjs-launcher": "1.0.4",
        "karma-phantomjs-shim": "1.5.0",
        "karma-sinon-chai": "2.0.2",
        "karma-sourcemap-loader": "0.3.7",
        "karma-spec-reporter": "0.0.32",
        "karma-webpack": "3.0.5",
        "karma-webpack-grep": "1.0.1",
        "lodash-ts-imports-loader": "1.2.0",
        "mocha": "5.2.0",
        "mocha-webpack": "1.1.0",
        "node-sass": "4.10.0",
        "phantomjs-prebuilt": "2.1.16",
        "prettier": "1.12.1",
        "rimraf": "2.6.2",
        "sass-loader": "7.0.1",
        "sinon": "5.1.1",
        "sinon-chai": "3.2.0",
        "source-map-support": "0.5.4",
        "style-loader": "0.21.0",
        "ts-loader": "3.1.1",
        "ts-node": "3.3.0",
        "tslint": "5.9.1",
        "tslint-loader": "3.6.0",
        "tslint-no-unused-expression-chai": "0.1.4",
        "typescript": "2.8.3",
        "uglifyjs-webpack-plugin": "1.2.7",
        "url-loader": "1.0.1",
        "vue-cli": "2.8.2",
        "vue-loader": "14.2.2",
        "vue-style-loader": "4.1.2",
        "webpack": "3.11.0",
        "webpack-bundle-analyzer": "2.13.1",
        "webpack-hot-middleware": "2.22.1",
        "webpack-merge": "4.1.4",
        "webpack-node-externals": "1.7.2"
```
* Environment: Dev

**Comment by mroderick** [comment]
Edited code example to add syntax highlighting

**Comment by mroderick** [comment]
The code is not JavaScript. Could you provide a minimal, runnable example at jsbin or similar that shows the issue?

**Comment by fatso83** [comment]
Also, have you tried the simplest thing that often seems to fix things; delete the node_modules folder and reinstall?

**Comment by mroderick** [comment]
It's been a month, with no reply from OP. I am closing this
