### ISSUE TITLE
Stub does not mock the original function when runinng the test

### ISSUE THREAD

**Issue by slim-hmidi** [sinonjs/sinon#2033]
**Describe the bug**
I want to mock a function using `stub`, but when I run the test, the app execute the original function and not the stub.

**Expected behavior**
The original function will be mocked when running the test.

app.js:

```
const express = require('express');
const { isValid } = require('./utils/index');

const config = require('./config.json')[process.env.NODE_ENV || 'development']


const app = express();

app.get('/', (req, res)=> {


    const url = config.url;
   try {
    const validUrl = isValid(url)
    .then(() => {
        return res.redirect(`https://${url}`);
    })
    .catch(() => {
        return res.status(400).send('Unable to redirect to the given url');
    })
   } catch(error) {
      return res.send('Internal Server Error') 
   }




})

const port = process.env.port || 3000;

const server = app.listen(port, ()=> {
    console.log('server listens on 127.0.0.1:3000');
})

module.exports = {server, app};

```
config.json:

```
{
"development": {
    "url": "www.stackoverflow.com"
}, 
"test": {
    "url": "fake url"
}

}
```
utils/index.js:
```
const http = require('http');


module.exports.isValid = (url) => {
    const options = {
        method: 'HEAD',
        host: url
    }
const promise = new Promise((resolve, reject) => {
    const req = http.request(options, () => {
        return resolve(true)
    })
    req.on('error', () => {
        return reject(new Error('Not valid'))
    })

    req.end();
})

return promise;
}

```
test/index.js:
```
const request = require('supertest');
const chai = require('chai');
const sinon = require('sinon');
const index = require('../utils/index')
const { expect } = chai;

const { server } = require('../app');
const {url} = require('../config.json')['test'];



describe('isValid Test', () => {

    it('Should redirects an error when the url is not valid', async() => {

        const stub = sinon.stub(index, 'isValid');
        stub.withArgs(url).returns(Promise.reject(new Error('Not Valid')));
        const { status } = await request(server).get('/');

        expect(status).to.equal(400);

    })
})

```

error:
```
(node:23622) UnhandledPromiseRejectionWarning: Error: Not Valid
    at Context.it (/home/hs/perso/mockTests/chaiMock/test/index.js:17:52)
    at callFn (/home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runner.js:535:10)
    at /home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runner.js:653:12
    at next (/home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runner.js:447:14)
    at /home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runner.js:457:7
    at next (/home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runner.js:362:14)
    at Immediate.<anonymous> (/home/hs/perso/mockTests/chaiMock/node_modules/mocha/lib/runner.js:425:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:23622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
url:  www.stackoverflow.com
    1) Should redirects an error when the url is not valid


  0 passing (122ms)
  1 failing

  1) isValid Test
       Should redirects an error when the url is not valid:

      AssertionError: expected 302 to equal 400
      + expected - actual

      -302
      +400

      at Context.it (test/index.js:22:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

* Library version: 7.3.2
* Environment: Ubuntu 18.04.2LTS
* Example URL:
* Other libraries you are using: 
mocha: 6.1.4
chai: 4.2.0
supertest: 4.0.2

**Comment by fatso83** [comment]
This isn't a bug in Sinon. It's basically a usage question and has to do with how Sinon works. I have explained how this works (more than once) on StackOverflow, so you could for instance [check this answer out](https://github.com/sinonjs/sinon/issues/2033) :-)

**Comment by slim-hmidi** [comment]
@fatso83 thanks for your answer. But the sinon documentation is so poor and everytime I faced a problem I passed many hours to check and look for an answer in different places to resolve my issue. I think it's the time to update the documentation and write as much examples as possible to manipulate the library easily.

**Comment by fatso83** [comment]
Don't know how I missed pasting the wrong link. Fixed it now, if you want to read it.

This is basically about about not understanding how Javascript works, not Sinon, so it doesn't belong in the API docs. _But_, although it has zero to do with Sinon _technically_, I totally agree that we could use more examples in the documentation! Both this and [lots of other use cases](https://github.com/sinonjs/sinon/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adocumentation). But this has been up before and no one contributed ... Today we still just [have one How To](https://sinonjs.org/how-to/). But if you are willing to provide one, we are very open to additions! :smile_cat:
