### ISSUE TITLE
useFakeTimers shows "TypeError: Cannot set property performance of #<Window> which has only a getter" since 6.0.0

### ISSUE THREAD

**Issue by aphofstede** [sinonjs/sinon#2035]
**Describe the bug**
Using `const clock = sinon.useFakeTimers()` throws an error since v6.0.0 when using mocha, webpack and jsdom:
```
  1) AutoComplete
       supports offline search options:
     TypeError: Cannot set property performance of #<Window> which has only a getter
      at hijackMethod (node_modules/sinon/pkg/sinon-esm.js:20193:1)
      at Object.install (node_modules/sinon/pkg/sinon-esm.js:20665:1)
      at createClock (node_modules/sinon/pkg/sinon-esm.js:20697:1)
      at useFakeTimers (node_modules/sinon/pkg/sinon-esm.js:20713:1)
      at Sandbox.useFakeTimers (node_modules/sinon/pkg/sinon-esm.js:34317:1)
      at Context.<anonymous> (.tmp/mocha-webpack/1559254193536/frontend/test/autocomplete.spec.js:92:1)
```

**To Reproduce**
The test:
```
    it('supports offline search options', () => {
        const clock = sinon.useFakeTimers()
[...]
        clock.tick(500)
[...]
        clock.restore()
    })
```

**Expected behavior**
The clock is mocked.

**Context (please complete the following information):**

* Library version: All versions >= 6.0.0
* Environment: mocha-webpack, jsdom

**Additional context**
**Workaround**: Since v7.1.1, using `const clock = sinon.useFakeTimers({ global })` seems to work around the issue.

**Comment by fatso83** [comment]
Thank you. This needs to be solved by `lolex`, as it's basically sinonjs/lolex#243
