### ISSUE TITLE
Sinon.stub() not replacing the function

### ISSUE THREAD

**Issue by PradeepSmg** [sinonjs/sinon#2066]
Sinon.stub is not replacing the function instead calling the original function.

[https://stackoverflow.com/questions/57037277/sinon-stub-not-working-and-calling-the-original-function](url)

Actual output :

> (node:5353)` UnhandledPromiseRejectionWarning: Error: Invalid username
`
    at Client.connect (/Users/z003878/Network_API/NetworkApi/network-switch-configurations-v1-maccheckportbounce/node_modules/ssh2/lib/client.js:182:11)
    at Promise (/Users/z003878/Network_API/NetworkApi/network-switch-configurations-v1-maccheckportbounce/app/maccheckportbounce.js:78:10)
    at new Promise (<anonymous>)
    at performportTrunkCheck (/Users/z003878/Network_API/NetworkApi/network-switch-configurations-v1-maccheckportbounce/app/maccheckportbounce.js:50:12)
    at Promise (/Users/z003878/Network_API/NetworkApi/network-switch-configurations-v1-maccheckportbounce/app/maccheckportbounce.js:112:36)
    at new Promise (<anonymous>)
    at Object.performMaccheckPortbounce (/Users/z003878/Network_API/NetworkApi/network-switch-configurations-v1-maccheckportbounce/app/maccheckportbounce.js:83:10)
    at Context.<anonymous> (/Users/z003878/Network_API/NetworkApi/network-switch-configurations-v1-maccheckportbounce/test/maccheckportbounce-test.spec.js:72:32)
    at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:525:10)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:643:12
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:437:14)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:447:7
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:362:14)
    at /usr/local/lib/node_modules/mocha/lib/runner.js:410:7
    at done (/usr/local/lib/node_modules/mocha/lib/runnable.js:334:5)
    at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:410:7)
    at Hook.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:379:7)
    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:382:10)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runner.js:415:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
(node:5353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
