### ISSUE TITLE
Test fail

### ISSUE THREAD

**Issue by guimard** [sinonjs/sinon#2225]
**Describe the bug**

A simple `npm i && npm run test-node` fails with this message:
```
  1401 passing (1s)
  12 pending
  1 failing

  1) issues
       #1456
         "after each" hook for "stub window innerHeight":
     TypeError: Cannot read property 'restore' of undefined
      at Context.<anonymous> (test/issues/issues-test.js:333:21)
      at callFn (/usr/share/nodejs/mocha/lib/runnable.js:395:21)
      at Hook.Runnable.run (/usr/share/nodejs/mocha/lib/runnable.js:382:7)
      at next (/usr/share/nodejs/mocha/lib/runner.js:384:10)
      at Immediate._onImmediate (/usr/share/nodejs/mocha/lib/runner.js:428:5)
```

NB: I'm using mocha 7

**Comment by mroderick** [comment]
It's a bit unclear to me what this issue is about.

Is this a checkout of Sinon `master` branch?
If so, why are you using `mocha@7`?

**Comment by mroderick** [comment]
If you would like to contribute a PR to upgrade Sinon to use `mocha@7`, then the failing test is in `test/issues/issues-test.js:333`, which is a test to prevent regressions of an old issue.

It looks like reading the `mocha` changelog might be required to figure out why this test starts failing. There could be a regression in `mocha@7`

**Comment by fatso83** [comment]
I am not sure even what it means that you are using Mocha 7. We are not. And if you use `npm run test-node` it will use the `mocha` script that first shows in your path, which will be `./node_modules/.bin`, as this is dynamically added as the first folder when running NPM scripts. So if you have installed Mocha 7 globally using `npm i mocha -g` it does not matter.

**Comment by guimard** [comment]
@fatso83: you're right, test fails simply

**Comment by mroderick** [comment]
@guimard you didn't answer my original question.

Why are you testing Sinon with Mocha 7?

**Comment by guimard** [comment]
@mroderick : I'm Debian Developper and I've to rebuild sinon from source & test with Debian shared libraries.

However, test fail locally with `node_module/.bin/mocha`, so it's not related to mocha 7.

Cheers,

**Comment by mroderick** [comment]
```
npm ci
npm test
```

Does this fail for you?

**Comment by guimard** [comment]
Hi,

here is the report:
```
$ npm ci

> puppeteer@2.1.0 install /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/puppeteer
> node install.js

Downloading Chromium r722234 - 121.1 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/puppeteer/.local-chromium/linux-722234

> fsevents@1.2.11 install /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/fsevents
> node-gyp rebuild

make : on entre dans le répertoire « /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/fsevents/build »
  SOLINK_MODULE(target) Release/obj.target/.node
  COPY Release/.node
make : on quitte le répertoire « /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/fsevents/build »

> puppeteer@1.20.0 install /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/mochify/node_modules/puppeteer
> node install.js

Downloading Chromium r686378 - 114 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/mochify/node_modules/puppeteer/.local-chromium/linux-686378

> husky@4.2.1 install /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.1 postinstall /home/xavier/dev/debian/src/pkg-js/packages/node-sinon/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:                                                                                                                                         
> https://opencollective.com/husky/donate

added 869 packages in 99.5s

$ npm test

> sinon@9.0.0 test /home/xavier/dev/debian/src/pkg-js/packages/node-sinon
> run-s test-node test-headless test-webworker test-esm


> sinon@9.0.0 test-node /home/xavier/dev/debian/src/pkg-js/packages/node-sinon
> mocha --recursive -R dot "test/**/*-test.js"



  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․․․,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․․․․,

․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․․․․․․․,․,․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,,․․․․․․․․․․․․․․,․,․․․․․․․․․․․․․․․․․․

  1401 passing (1s)
  12 pending


> sinon@9.0.0 test-headless /home/xavier/dev/debian/src/pkg-js/packages/node-sinon
> mochify --no-detect-globals --recursive -R dot --grep WebWorker --invert --plugin [ proxyquire-universal ] "test/**/*-test.js"

Error: Failed to launch chrome!
[0309/141654.877745:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55b46f6c7879 base::debug::CollectStackTrace()
#1 0x55b46f624c63 base::debug::StackTrace::StackTrace()
#2 0x55b46f639013 logging::LogMessage::~LogMessage()
#3 0x55b470dd395e service_manager::ZygoteHostImpl::Init()
#4 0x55b46f268adc content::ContentMainRunnerImpl::Initialize()
#5 0x55b46f2b472c service_manager::Main()
#6 0x55b46f2670b1 content::ContentMain()
#7 0x55b46f2b399d headless::(anonymous namespace)::RunContentMain()
#8 0x55b46f2b370b headless::HeadlessShellMain()
#9 0x55b46d0441b8 ChromeMain
#10 0x7fa6a6627bbb __libc_start_main
#11 0x55b46d04402a _start

Received signal 6
#0 0x55b46f6c7879 base::debug::CollectStackTrace()
#1 0x55b46f624c63 base::debug::StackTrace::StackTrace()
#2 0x55b46f6c7401 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7fa6a8aaf520 <unknown>
#4 0x7fa6a663af61 gsignal
#5 0x7fa6a6626535 abort
#6 0x55b46f6c6265 base::debug::BreakDebugger()
#7 0x55b46f639461 logging::LogMessage::~LogMessage()
#8 0x55b470dd395e service_manager::ZygoteHostImpl::Init()
#9 0x55b46f268adc content::ContentMainRunnerImpl::Initialize()
#10 0x55b46f2b472c service_manager::Main()
#11 0x55b46f2670b1 content::ContentMain()
#12 0x55b46f2b399d headless::(anonymous namespace)::RunContentMain()
#13 0x55b46f2b370b headless::HeadlessShellMain()
#14 0x55b46d0441b8 ChromeMain
#15 0x7fa6a6627bbb __libc_start_main
#16 0x55b46d04402a _start
  r8: 0000000000000000  r9: 00007ffc898f3350 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffc898f4618 r13: 00007ffc898f35f8 r14: 00007ffc898f35f8 r15: 00007ffc898f3610
  di: 0000000000000002  si: 00007ffc898f3350  bp: 00007ffc898f35a0  bx: 00007fa6a67bb840
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fa6a663af61  sp: 00007ffc898f3350
  ip: 00007fa6a663af61 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinon@9.0.0 test-headless: `mochify --no-detect-globals --recursive -R dot --grep WebWorker --invert --plugin [ proxyquire-universal ] "test/**/*-test.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sinon@9.0.0 test-headless script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xavier/.npm/_logs/2020-03-09T13_16_55_125Z-debug.log
ERROR: "test-headless" exited with 1.
npm ERR! Test failed.  See above for more details.
```

**Comment by fatso83** [comment]
@guimard It seems like the problem has shifted, because all "normal" tests ran fine on Node. What I see now is Chrome having a core dump, thus failing to run the tests. This seems like a basic problem with Puppeteer/Chromium running on Debian, not Sinon itself.

**Comment by fatso83** [comment]
>  I'm Debian Developper and I've to rebuild sinon from source & test with Debian shared libraries.

@guimard May I suggest just using our pre-built packages in `/pkg` to avoid the issue? I am not sure what this is about, but whatever the reason, if you get a build going then you should end up with identical packages in any case.

**Comment by guimard** [comment]
@fatso83: mocha test ils enough for me: I'm [Debian project](https://www.debian.org) member and I'm maintainer of sinon for Debian.

Cheers,
Xavier
