### ISSUE TITLE
Stub is called, but doesn't increase the called counter

### ISSUE THREAD

**Issue by vytas-dauksa** [sinonjs/sinon#2240]
**Describe the bug**
Stub gets called, but returns wrong called status

**To Reproduce**
// file.js
```
const logger      = require('logger')();
const request     = require('request-promise-native');

module.exports = ({module}) => {
    async function toTest(body) {
        try {
            const response = await request.post({
            uri: 'http://example.com',
            body: { body },
            json: true,
            gzip: true
            });
        } catch(err) {
            logger.error({module}, 'Failed');
        }
    }

    return { toTest };
};
```

// test-file.js
```
const expect = require('chai').expect;
const sinonjs = require('sinon');
const proxyquire = require('proxyquire').noPreserveCache();

describe('file', () => {
        let loggerMock = {};
    let requestPostMock = () => { throw new Error("Not implemented Mock") };
        let File;
    before( () => {
        File = proxyquire.noCallThru().load('./file', {
            'request-promise-native': { post: async () => { return await requestPostMock(); }},
            'logger': function() { return loggerMock; }
        });
    });

        let file;
        beforeEach( () => {
                file = File({ module: "testFile"});
        });

        afterEach( () => {
                loggerMock = {};
        requestPostMock = () => { throw new Error("Not implemented Mock") };
                file = null;
        });

    describe('toTest', () => {
        let loggerErrorStub;
        let sinon;
        beforeEach( () => {
            sinon = sinonjs.createSandbox();
            loggerErrorStub = sinon.stub().callsFake(() => {console.log("loggerErrorStub was called!")});
            loggerMock.error = loggerErrorStub;
        });

        afterEach( () => {
           sinon.restore()
        });

        it('should not log on success', async () => {
            requestPostMock = () => { console.log("Going to succeed"); return "success" }

            const response = await file.toTest({});

            expect(loggerErrorStub.notCalled).to.be.true;
        });

        it('should log on failure', async () => {
            requestPostMock = () => { console.log("Going to fail"); throw new Error("failed") }

            const response = await file.toTest({});

            expect(loggerErrorStub.calledOnce).to.be.true;
        });
    });
});
```

mocha output:
```
  file
    toTest
Going to succeed
      ✓ should not log on success
Going to fail
loggerErrorStub was called!
      1) should log on failure


  1 passing (15ms)
  1 failing

  1) file
       toTest
         should log on failure:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/test-file.js:53:49)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Expected behavior**
Both tests should pass, if I swap them around - they pass.

**Context (please complete the following information):**

* Library version: sinon 7.5.0
* Environment: Mac
* Other libraries you are using:
mocha 6.2.2, chai 4.2.0, proxyquire 2.1.3

**Comment by vytas-dauksa** [comment]
Also tried sinon 9.0.1 & mocha 7.1.1

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
