### ISSUE TITLE
TypeError: Cannot read property 'every' of undefined

### ISSUE THREAD

**Issue by joaopedr0vieira** [sinonjs/sinon#2399]
**Describe the bug**
`TypeError: Cannot read property 'every' of undefined
at Object.<anonymous> (node_modules/sinon/node_modules/@sinonjs/commons/lib/called-in-order.js:3:42)
at Object.<anonymous> (node_modules/sinon/node_modules/@sinonjs/commons/lib/index.js:5:20)`

**To Reproduce**
Started getting this error just after stopping jest watch mode and then started again with no changes in the code

**Expected behavior**
Run tests

**Screenshots**
![image](https://user-images.githubusercontent.com/79520707/132760184-5ba5130e-1e39-4dc4-b7fb-5d38316aa379.png)

**Context (please complete the following information):**

- Library version: ^11.1.2
- Environment: Windows 10, Node.js v14.17.0
- Example URL:
- Other libraries you are using: sequelize-test-helpers (might be this)

**Additional context**

**Comment by joaopedr0vieira** [comment]
Closed and re-opened the terminal and solved, lol

**Comment by joaopedr0vieira** [comment]
actually, starting getting this error again

**Comment by joaopedr0vieira** [comment]
Find the problem, jest was mocking all imports
