### ISSUE TITLE
Broken Documentation links on main page

### ISSUE THREAD

**Issue by srknzl** [sinonjs/sinon#2432]
Are you aware of broken links in the documentation? Like this link: https://sinonjs.org/releases/v13.0.0 and all other releases.

**Comment by fatso83** [comment]
Yup, I just found out. There was something about #2426 that did not pan out that well.

cc @cincodenada

**Comment by fatso83** [comment]
On the [github build action log for the Github pages build](https://github.com/sinonjs/sinon/runs/4981176163?check_suite_focus=true) (authorized only) we got this error:
```
Run actions/jekyll-build-pages@v1-beta
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv1beta_2cd4c6 --label 84217e --workdir /github/workspace --rm -e INPUT_SOURCE -e INPUT_DESTINATION -e INPUT_FUTURE -e INPUT_BUILD_REVISION -e INPUT_VERBOSE -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e ACTIONS_ID_TOKEN_REQUEST_URL -e ACTIONS_ID_TOKEN_REQUEST_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sinon/sinon":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1-beta
/usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (/github/workspace/./docs/_config.yml): could not find expected ':' while scanning a simple key at line 8 column 1 (Psych::SyntaxError)
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/configuration.rb:143:in `safe_load_file'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/configuration.rb:180:in `read_config_file'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/configuration.rb:207:in `block in read_config_files'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/configuration.rb:205:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/configuration.rb:205:in `read_config_files'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll.rb:113:in `configuration'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/command.rb:43:in `configuration_from_options'
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:29:in `process'
	from /usr/local/bundle/gems/github-pages-223/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-223/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
  Logging at level: debug
github-pages 223 | Error:  (/github/workspace/./docs/_config.yml): could not find expected ':' while scanning a simple key at line 8 column 1
```

Probably some script that fails to set some value.

**Comment by srknzl** [comment]
Thanks it's fixed! 🎉

**Comment by tleunen** [comment]
v13 doesn't seem to be on npm yet

**Comment by fatso83** [comment]
@tleunen That's right. #2434 fixed that. A `--dry-run` had slipped in through a test commit before merging.
