### ISSUE TITLE
resetting in invoke protection makes crash on .throws stub

### ISSUE THREAD

**Issue by topia** [sinonjs/sinon#586]
51e692ab3020c1f87810452d08781b500ae7653f makes bad result with .throws.

-- index.js

``` js
var sinon = require('sinon');

mock = sinon.stub();
mock.throws('dummy error');

try {
    mock();
} catch (e) {
    console.log(e.toString());
}

mock.reset();
```

-- package.json

``` json
{
  "name": "sinon-bug-temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sinon": "^1.11.0"
  }
}
```

-- (result)

```
% node index.js
dummy error

/tmp/sinon-bug-temp/node_modules/sinon/lib/sinon/spy.js:89
                    throw err;
                          ^
InvalidResetException: Cannot reset Sinon function while invoking it. Move the call to .reset outside of the callback.
    at Function.spyApi.reset (/tmp/sinon-bug-temp/node_modules/sinon/lib/sinon/spy.js:86:31)
    at Object.<anonymous> (/tmp/sinon-bug-temp/index.js:12:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

-- (expected)

```
dummy error
```

**Comment by newdaveespionage** [comment]
Note for anyone finding this from Google when running tests on modules, you're probably missing the 'new' keyword somewhere in your instantiation.
