### ISSUE TITLE
property getter broken in 1.17.0

### ISSUE THREAD

**Issue by MaerF0x0** [sinonjs/sinon#847]
The following code works in 1.16.1 but fails in 1.17.0
(with mocha and mongodb)

```coffeescript 
sinon = require 'sinon'
assert = require 'assert'

describe "mock collection", ->
   beforeEach ->
     @collection = sinon.createStubInstance(Collection)
     sinon.stub @collection, 'collectionName', get: -> 'users'

   it 'should return users', ->
     assert.equal @collection.collectionName , 'users'
```
Will throw this err: 

```
1) permissions: scoped_query "before each" hook:
     TypeError: Cannot read property 'name' of undefined
    at [object Object].Object.defineProperty.get [as collectionName] (/Users/user/code/api/node_modules/mongodb/lib/collection.js:130:52)
    at /Users/user/code/api/node_modules/sinon/lib/sinon/walk.js:34:43
    at Array.forEach (native)
    at walk (/Users/user/code/api/node_modules/sinon/lib/sinon/walk.js:33:45)
    at Object.walk (/Users/user/code/api/node_modules/sinon/lib/sinon/walk.js:39:17)
    at Object.stub (/Users/user/code/api/node_modules/sinon/lib/sinon/stub.js:52:23)
    at Object.sinon.createStubInstance (/Users/user/code/api/node_modules/sinon/lib/sinon/util/core.js:361:26)
    at Context.<anonymous> (/Users/user/code/api/test/permissions.coffee:277:7)
    at Hook.Runnable.run (/Users/user/code/api/node_modules/mocha/lib/runnable.js:200:32)
    at next (/Users/user/code/api/node_modules/mocha/lib/runner.js:201:10)
    at /Users/user/code/api/node_modules/mocha/lib/runner.js:212:5
    at process._tickDomainCallback (node.js:492:13)
```

For reference that line looks like:
```javascript
Object.defineProperty(Collection.prototype, 'collectionName', {
  enumerable: true, get: function() { return this.s.name; }
});
```

**Comment by mrjackdavis** [comment]
I'm having a similar problem, where createStubInstance is throwing an error.

    var sequelize = sinon.createStubInstance(Sequelize);

results in:

    TypeError: Cannot read property 'getConnectorManager' of undefined
      at Object.defineProperty.get (node_modules/sequelize/lib/sequelize.js:279:35)
      at node_modules/sinon/lib/sinon/walk.js:34:43
      at Array.forEach (native)
      at walk (node_modules/sinon/lib/sinon/walk.js:33:45)
      at Object.walk (node_modules/sinon/lib/sinon/walk.js:39:17)
      at Object.stub (node_modules/sinon/lib/sinon/stub.js:52:23)
      at Object.sinon.createStubInstance (node_modules/sinon/lib/sinon/util/core.js:361:26)
      at Context.<anonymous> (tests/unit/_ContactStoreTests.js:16:26)

Works in version `1.16.x` but fails in `1.7.0`

**Comment by fatso83** [comment]
Seems like the regression was introduced by 079b00feb99c41174c8de62299a5f6c5c94cb56c.
@traviskaufman : any idea what is happening?

**Comment by traviskaufman** [comment]
I believe this has to do with `walk` not handling getters properly. Looking into it now.

**Comment by traviskaufman** [comment]
Yeah this was happening because `walk` was not invoking accessors defined on prototype objects on the _original_ receiving objects, therefore trying to dereference a non-existent property. Submitted a PR with a fix.

**Comment by traviskaufman** [comment]
https://github.com/sinonjs/sinon/pull/857
