### ISSUE TITLE
Prototype chain and stub breaking behaviours between 1.16.1 and 1.17.1

### ISSUE THREAD

**Issue by Spy-Seth** [sinonjs/sinon#867]
I've spot another BC behavior between sinon 0.16.1 and sinon 0.17.1. I've see https://github.com/sinonjs/sinon/issues/860 but I'm not sure this is the same problem.

This code do not throw any error with sinon 1.16.1:

```javascript
'use strict';

var sinon = require('sinon');

var A = function A() {
    console.log('> Hello A');
};

A.prototype.foo = function foo() {
    return 42;
};


var B = function B() {
    console.log('> Hello B');
};

B.prototype = new A();

B.prototype.foo = function foo() {
    return 51;
};

var b = sinon.createStubInstance(B); // works in 1.6.1, error in 1.7.1 (see below)
```

In 1.7.1, the last line trigger this error: 

```
TypeError: Attempted to wrap foo which is already wrapped
    at checkWrappedMethod (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/util/core.js:81:29)
    at Object.wrapMethod (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/util/core.js:121:21)
    at stub (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/stub.js:67:26)
    at /Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/stub.js:60:25
    at /Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:26:26
    at Array.forEach (native)
    at walkInternal (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:23:45)
    at walkInternal (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:31:17)
    at walkInternal (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:31:17)
    at Object.walk (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:46:20)
--------------
Error: Stack Trace for original
    at Object.wrapMethod (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/util/core.js:140:34)
    at stub (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/stub.js:67:26)
    at /Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/stub.js:60:25
    at /Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:26:26
    at Array.forEach (native)
    at walkInternal (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:23:45)
    at walkInternal (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:31:17)
    at Object.walk (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/walk.js:46:20)
    at Object.stub (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/stub.js:52:23)
    at Object.sinon.createStubInstance (/Users/spy-seth/workspace/myproject/node_modules/sinon/lib/sinon/util/core.js:361:26)
```

**Comment by mantoni** [comment]
Thanks for reporting. I'm running into this as well. I'm looking into it right now. It is somewhat related and I might be able to fix both issues.

**Comment by Spy-Seth** [comment]
Thank for the fix :+1:
